version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - db_data:/app
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:/app/llmkit.db
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - JWT_SECRET=${JWT_SECRET}

  ui:
    build:
      context: ./ui
      args:
        - API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db_data:
