services:
  backend:
    build: ./backend
    volumes:
      - db_data:/app/data
    environment:
      - RUST_LOG=${RUST_LOG}
      - DATABASE_URL=${DATABASE_URL}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - USE_SECURE_COOKIE=${USE_SECURE_COOKIE}

  ui:
    build:
      context: ./ui
      args:
        API_BASE_URL: ${API_BASE_URL}
    depends_on:
      - backend

volumes:
  db_data:
